### ISSUE TITLE
Comments for Entity Prefabs

### ISSUE THREAD

**Issue by Best-JelloBeanz** [Brim7Premium/Calamity-Reign-of-Yharim#1]
For documentation, and readability going into the future of the development of  _Calamity: Reign of _Yharim's__ code, I suggest that comments be added to the entity prefabs that explain the function of  portions and/or specific lines of code, in as much detail deemed necessary or helpful, for other programmers that may join the project in the future.
Though I am unfamiliar with Unity, if I have the basic idea of how each part of a program works, and how the interact, I can likely provide feedback that would assist with development until we get more qualified programmers to assist with the project.

**Comment by Brim7Premium** [comment]
Yes, I plan to comment everything on the entity code. In its current state,
I don't even understand what it's doing, as fazin coded it. I plan to look
into it and comment on everything so it will be easier for me, you, and
future programmers to understand.

**Comment by Brim7Premium** [comment]
I will work on this. I'm also going to try to understand and document some of the other things in the project like the utils script and the parallax background script.

**Comment by Best-JelloBeanz** [comment]
Sorry for the inconvenience, I apparently mistook prefabs for the actual ai of the enemies. 
While I was browsing through the code I found the ai package in the scripts package. 
It seems that prefabs controll the actual creation of new instances of objects rather than controll the actual behavior, so understanding this now I'll do my best to add documentation for prefabs in my own branch. 

I think that having .txt files in each package explaining the contents and other relevant information, and/or expanding the README file, with a table of contents. to fulfill the same purpose.

**Comment by Brim7Premium** [comment]
Yea, the prefabs are just there so we can drag and test enemies (and save them), the AI scripts in the AI folder controls the AI. I still want to add comments to the scripts so I can understand them better, but yes, I will add some txt files in each folder explaining what they are used for.
