### ISSUE TITLE
Enemies spawn in blocks

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#11]
Also self-explanatory. This might be an easy fix though, I haven't really checked the enemyspawner script in a while.

**Comment by Best-JelloBeanz** [comment]
This issue was fixed by psychoFungus two weeks ago, so I'll close this one now.

**Comment by Brim7Premium** [comment]
I'll have to look through that and add them back, as most of those changes I didn't add to my branch due to not knowing what they were, and because the movement changes were not beneficial

**Comment by Brim7Premium** [comment]
I didn't realize there were any other things besides changes to the movement

**Comment by Brim7Premium** [comment]
I would reccomend that psychofungus pulls from my branch that doesn't have any of their changes, and add the non-movement based changes to it following the new pull request rules here: https://docs.google.com/document/d/1FMGDXsRueJtzEOoHVdwF-asd1nC4_8H72XCxNc703mE/edit?usp=sharing
