### ISSUE TITLE
Performance issues with entities

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#21]
High amounts of entities (Npcs and projectiles) will cause the game to lag.

**Comment by Best-JelloBeanz** [comment]
Is this still problematic?
It'd be helpful to know how the estimated amount of entities the game can actually handle, and if that number of entities could ever be realistically reached by the game, especially in the open demo.

**Comment by Brim7Premium** [comment]
@Best-JelloBeanz Having every segment of DoG fire a projectile lagged the game bad. It was the same with letting too many slimes spawn. The number was pretty low (under 40) and it is a number the game would realistically reach.

**Comment by psychoFungus** [comment]
Every projectile and NPC called every frame gameObject.Find. No wonder it was lagging.

**Comment by Brim7Premium** [comment]
@psychoFungus Why is it doing this? (I don't really remember the NPC code)

**Comment by psychoFungus** [comment]
@Brim7Premium I rewrote most of the code of this classes. If I'm giving my honest opinion about the previous code I'm going to prison.

**Comment by Best-JelloBeanz** [comment]
Is this still an issue? 
That on video GuardBoi sent in the discord definitely showed that the game could handle a lot more entities before.
