### ISSUE TITLE
Improved Slope Handling

### ISSUE THREAD

**Issue by Best-JelloBeanz** [Brim7Premium/Calamity-Reign-of-Yharim#31]
Currently, the player character can run up slopes without any clear issues with the physics, but the player jumps when reaching the top of a slope, and the player character does not stay on the ground when running down the slope.

I'll need to look into this myself later because this is just a repeat of what Brim posted on the Trello, and there is no current visual documentation of the issues. 
More context needed on other functionality regarding slopes as well.

**Comment by Brim7Premium** [comment]
If you are talking about jumping up a wall with a slope on top and having the player's legs get put in the ground, this is because the player's physics are being used and not the floating code

**Comment by Brim7Premium** [comment]
Or you might want to update your branch
