### ISSUE TITLE
Basic Inventory & UI

### ISSUE THREAD

**Issue by Best-JelloBeanz** [Brim7Premium/Calamity-Reign-of-Yharim#32]
A large part of the game relies on inventory, so we kind of need this.

These are only the bare essentials we need to develop a more proper inventory system later, and it is recommended that the implementation of other inventory features is not to be attempted before the following features are present.

**Basic Inventory Requirements**
- [x] Basic Placeholder sprites
- [x] Inventory opens on use of defined Keybind
- [x] Items added into the inventory, are automatically stored in next available slot
- [x] An item's sprite is displayed in the inventory slot it is stored in
- [x] Items can be moved manually to other slots with cursor
- [x] An item's sprite is displayed when held by the cursor
- [x] Hotbar Swapping 
- [x] Active hotbar slot is highlighted
- [x] Items can be removed from inventory 

**Related Issues**
- #36

**Comment by psychoFungus** [comment]
I'll try to finish this.

**Comment by Brim7Premium** [comment]
Don't. I plan to finish this in a specific way. Do you think you could help @mariohero24 with installing the project? There has been quite a few problems, and you've most recently installed it.

**Comment by psychoFungus** [comment]
I'll try help him when he is online. Anything I can do besides this?

**Comment by Brim7Premium** [comment]
I'll open a new issue

**Comment by Brim7Premium** [comment]
@psychoFungus I've "finished" it, but it still needs some polishing and some of the stuff I made was coded pretty badly. The changes can be found on my branch if you can work on it.

**Comment by Brim7Premium** [comment]
This task is now "complete" but not done very well internally I believe. Before this is marked as done, it should probably be looked at by another programmer.

**Comment by Brim7Premium** [comment]
They're on maintesting now
