### ISSUE TITLE
Resolution and building the project

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#50]
Currently, the play menu is displayed at FullHD (1920x1080). I don't know if this is the correct display resolution, or anything really about resolution. A similar issue is building the project. Whenever the project is built, a bunch of things are messed up in windowed mode when the window is stretched. A more extensive list of resolution problems would likely help us figure out what exactly is wrong.

**Comment by psychoFungus** [comment]
If it's not at standard resolution, then just lock scalability.

**Comment by Brim7Premium** [comment]
Yea, but are we going to want to have it that way forever?

**Comment by psychoFungus** [comment]
No, at some point we'll have to change it. If you want you can add resolution parameter in settings like in most games.
