### ISSUE TITLE
Non-mechanical differences between main and 115101120

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#52]
115101120 and main should work exactly the same with only mechanical differences. However, every system that has been changed in 115101120 works differently and worse than the version in main. Technical changes are important, but if they are going to make the systems worse then there is a problem.

**Comment by psychoFungus** [comment]
I can't make this systems work exactly the same, but most of them(as I think) work very similar to the previous ones.  I know that there some issues with respawning, health bars and music, but everything?

**Comment by Brim7Premium** [comment]
let me quickly put some if the things I noticed immediately:
The movement isn't smooth and stops on slopes (don't know exactly, but definitely didn't feel as good or smooth as it did before)
The slimes are jumping in the air/jumping while falling
like 6 or 7 slimes spawned really fast initially, and then none spawned (I actually don't know if none spawned, I didn't run the project for that long, but I do know the speed at which they spawned changed)
I'll do some more testing later. (maybe we're at the stage were we could recruit beta-testers to better document issues?)

**Comment by psychoFungus** [comment]
I fixed all of what you said, respawning and health bars(i hope), except for movement, I have no idea what you are talking about. About beta-testers, they will be helpful but programmers do just fine.

**Comment by Brim7Premium** [comment]
I'll put a comparison on the server
