### ISSUE TITLE
Certain NPC healthbars cause an error

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#59]
Basically the title. Whenever the devourer of gods is spawned, it's healthbar immediately, constantly causes outside bounds errors

**Comment by psychoFungus** [comment]
Can you provide log? I wasn't able to replicate an error.

**Comment by psychoFungus** [comment]
Check if sprites are assigned in the devourer's prefab, this likely to cause an issue.

**Comment by Brim7Premium** [comment]
@psychoFungus no, the sprites are assigned. It appears that all other NPCs have the same problem other than green slime and dummy. Just try putting a their prefabs in the scene on Maintesting and you'll see what I mean

**Comment by psychoFungus** [comment]
Still no idea what causes an error but I found that I incorrectly assigned sprites. How many bar sprites do we have? Everywhere only 52 are assigned but files have 53. Healthbar_52 is empty and, as I understand, you don't use it?

**Comment by psychoFungus** [comment]
For some reason Healthbar_33 wasn't assigned, I'm gonna fix this.
