### ISSUE TITLE
Placeholder main menu completion 

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#63]
The placeholder main menu is incomplete, and completing it must be done before we can actually add functionality. I will explain below exactly what I had in mind for the placeholder main menu.
### First I'll go over what we already have:
The main menu, which contains 5 buttons: SINGLEPLAYER, MULTIPLAYER (crossed out), OPTIONS, ACHEIVEMENTS, EXIT GAME.
Multiplayer and exit game can be ignored, as exiting is already implemented and won't change, and multiplayer isn't something we should worry about right now.
The singleplayer button will lead to a deltarune/downfall of a cruel world style save screen with a difficulty button on the left and the save name, no save display, and the save time. there is also a name edit button on the top left of each save. The no save display should only appear when there is no save, but right now the creating save feature isn't implemented so nothing happens. A save creation menu exists in the files, but isn't implemented at the time. Clicking on an already-made save will bring you to the game.
### What needs to be done for the singleplayer menus:
Save creation: All saves should start out as completely empty rectangles, with only the no save display text and the difficulty indicator background square visible. When you click on a save like this, it will bring you to the save creation screen, where you can set your save name and difficulty. The done button on this screen cannot be pressed until both are set. Once that is pressed, it will send you back to the save view screen where your save will appear in the respective slot you clicked to create it. This save would act exactly like the placeholder saves that already exist in the project, just you would be able to make it instead of just seeing it. 
Settings can be ignored for now, as we don't really know what setting we will need. A list of possible settings under the already existing categories would be helpful.
Make sure to look at how these things are already implemented when you make these changes.

### Related Issues
- #30

**Comment by Brim7Premium** [comment]
I will update this when we get settings and when I make a placeholder achievement menu

**Comment by Brim7Premium** [comment]
@psychoFungus if you can, could you also implement the health bar using an actual slider that could be easily changed if we decide to resprite it?

**Comment by psychoFungus** [comment]
Save creation screen looks empty. Should there be any other settings?

**Comment by Brim7Premium** [comment]
not at the moment, no
