### ISSUE TITLE
Internal structure of items

### ISSUE THREAD

**Issue by Brim7Premium** [Brim7Premium/Calamity-Reign-of-Yharim#65]
How items will be internally structured and handled isn't known yet, and figuring that out is quite important. Currently, Items are just an inventory test, and none have functionality, but they do have data stored in scriptable objects. My idea was to originally have the scriptable objects store basic data like item type, name, ID, damage etc, but functionality would all be stored in one script, and item scriptable objects could call custom code from these main scripts based on settings changed for each item object. But after looking into calamity's code, I see that each item has a script with custom functionality and stuff. How exactly should we go about this? Should we have one script that is used by scriptable objects to determine the item's functionality, should we give each item a script, or should we do something else. 

**Related  Issues**
- #36

**Comment by psychoFungus** [comment]
What's the point of creating one single file? Separated files are easier to understand, manage and extend

**Comment by Brim7Premium** [comment]
Because we already have separate scriptableobjects for each item already.

**Comment by psychoFungus** [comment]
Can you unfold a little bit? I don't really understand where scriptableObjects used and why.

**Comment by Brim7Premium** [comment]
They are what is used by the guimanager to add and remove items from the inventory, and they contain all the universal data that all items have like sprite and ID

**Comment by Brim7Premium** [comment]
@psychoFungus Another reason I didn't want to use a separate script alongside the scriptableobjects would be that having three different files for every item might cause the game to be quite big in the future

**Comment by psychoFungus** [comment]
I think about creating something like default item prefab. Script will load all values necessary for the normal existence of an item from scriptableObject by ID and then pass the item to another script, that responds for item behaviour. And here better to use one large scriptableObject.

**Comment by Brim7Premium** [comment]
it wouldn't really be a scriptable object then

**Comment by Brim7Premium** [comment]
I think I understand now. We would implement items in a similar fashion to how NPCs work

**Comment by Brim7Premium** [comment]
@psychoFungus if you want to remake the system, I added the most recent item stuff to the maintesting branch.

**Comment by Brim7Premium** [comment]
@psychoFungus do you think you could remake the current item system so it doesn't use scriptable objects at all and just uses different item scripts?

**Comment by psychoFungus** [comment]
Can we use merged system? Every script will refer to a singe scriptable object. Items frequently switch between states so storing all parameters in one place would be useful.

**Comment by Brim7Premium** [comment]
That could just be a base class, could it not?

**Comment by psychoFungus** [comment]
I don't think we can save something like damage values for every weapon in the base class.

**Comment by Brim7Premium** [comment]
I'm just trying to stay close to how calamity/mods do it. Every item has a script under a base item class, and all values are set in each script

**Comment by Brim7Premium** [comment]
oh I understand what you mean here now. Damage would not be stored in the base class, rather inherited classes in each item script like mods do it

**Comment by psychoFungus** [comment]
As I understand, items would have three states: in the invenory, on the ground, in the hand. All of them have separate prefab. My idea is that all values that shouldn't be changed will be stored in scriptable object and only it can be passed between scripts. This can allow to have universal prefab for ground and inventory.

**Comment by Brim7Premium** [comment]
Well, the only reason we need to change the item system is because scriptable objects cannot hold data that is completely different for each object. What I mean is while they can hold data, the type of data is the same for each object and something that is unique to an object like how it attacks when swung would have to be the same for every object. If you have a working idea, could you implement it?

**Comment by psychoFungus** [comment]
What if we store all the base's script values in a scriptable object with additional inherited script? Script can be stored as a string with the class name. Basically my idea is to create three prefabs for different item states and modify them in runtime.

**Comment by Brim7Premium** [comment]
I'm gonna try to make this without scriptable objects

**Comment by psychoFungus** [comment]
What do you think about this system?

**Comment by guardboi** [comment]
Brimston was in vc with jello talking about having every item have its own prefab, no clue if thats what theyre gonna do

**Comment by Brim7Premium** [comment]
The idea was basically having items work in a similar sense to NPCs and projectiles, having a base class that has data which all items need, and each item would have an inherited class attached to the item. How the system currently works is that each different version of each item, such as the ground item or the item in the inventory, get information from somewhere about what item it should look like and have the data of instead of actually being the item. It has to get this data from an object in scene, so it uses scriptable objects, which are always loaded in scene. The problem here is that scriptable objects couldn't hold data specific to certain items, like swinging and projectile mechanics and behaviors, so we can't continue with this system without having to create even more scripts and make things even more confusing. The proposal is to have every instance of the item, whether it be in the inventory or on the ground, use one prefab with the required scripts attached like how NPCs do it.

**Comment by psychoFungus** [comment]
You mean one prefab for all states or one prefab per state?
I think its simply impossible or very time consuming to have one single prefab for all of the states. I thought about having one script for every of these prefabs but couldn't figure out how to easily merge current scripts.
Also I found a way to store scripts of any type in scriptabl objects which can allow for specific variables storing with help of static fields and if you didn't notice I made somewhat working item system.

**Comment by Brim7Premium** [comment]
@psychoFungus Have you pushed these changes to your branch yet

**Comment by psychoFungus** [comment]
yes

**Comment by Brim7Premium** [comment]
Can you explain how the scriptable objects access the script using a string variable? I don't quite understand how that works

**Comment by psychoFungus** [comment]
I convert 'string' to 'Type' and pass value to AddComponent. You can look in unity and c# docs for better understanding. Basically it just finds script by name.
