### ISSUE TITLE
Re-Structuring entity behavior & functionality

### ISSUE THREAD

**Issue by Best-JelloBeanz** [Brim7Premium/Calamity-Reign-of-Yharim#7]
Currently, entity behavior, specifically entity interactions seem to lack intuitive implementation and functionality. 
Initially I meant to make an issue on the entity collision system and provide feedback on that implimentation and specific ways we could improve, but through extensive research I realized the foundation of entity functionality is more bare-bones than I had assumed. 
I couldn't explain it better if I tried, so I provided a link that explains ideas I started to think of, and expands on them in more detail. The link below directs to an article on the use of interfaces, state machines and other relevant info which I can see us benefitting from.

https://gamedevbeginner.com/interfaces-in-unity/#comment-6091

Edit: The information provided also would assist specifically with the proposed hitbox system

**Comment by Brim7Premium** [comment]
Yes, I'm aware that our entity and player systems need work. I'm currently working on rewriting the playercontroller to use the NPC class, and (excessively) commenting the NPC class. I understand most of it, but there are some things I need to look into like delegates and everything related to that.

**Comment by Brim7Premium** [comment]
@Best-JelloBeanz So how do you think we should improve the collision system? We are currently using the built-in 2d physics to detect collisions between NPCs (i'm assuming you mean NPC collision, as the collision mechanics are in that script) The article is useful, but knowing this information won't be useful unless we know where to use it.

Also I found out that collisions between entities are being messed up by the item (while I was testing I found that entities aren't detecting the player gameobject, only the item one.

**Comment by Best-JelloBeanz** [comment]
I am closing this issue for now, there isn't any clear idea of what needed to be changed, and everything seems to be fine with collision last I checked. 
If entity collision does need changes, I'll just make a new issue describing what the problems actually are.
